AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'projeto para trabalho serverless'

Globals:
  Function:
    Timeout: 40
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TripTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://trips-fiap-335710/7edabe7fb0901ef8d5c3e94300ed013e
      Handler: br.com.trips.handler.CreateTrip::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        CreateTrip:
          Type: Api
          Properties:
            Path: /trips
            Method: post
  GetTripsByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://trips-fiap-335710/7edabe7fb0901ef8d5c3e94300ed013e
      Handler: br.com.trips.handler.GetTripsByCountry::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetTripsByCountry:
          Type: Api
          Properties:
            Path: /trips/{country}
            Method: get
          RequestParameters:
          - method.request.querystring.city
          - method.request.querystring.starts
          - method.request.querystring.ends
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
      - AttributeName: country
        AttributeType: S
      - AttributeName: travelDate
        AttributeType: S
      KeySchema:
      - AttributeName: country
        KeyType: HASH
      - AttributeName: travelDate
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateTripFunction:
    Description: CreateTrip
    Value:
      Fn::GetAtt:
      - CreateTripFunction
      - Arn
  GetTripsByCountryFunction:
    Description: GetTripsByCountry
    Value:
      Fn::GetAtt:
      - GetTripsByCountryFunction
      - Arn
