AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: trips projects
Globals:
  Function:
    Timeout: 40
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TripTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://trips-bucket/cb9f89b3d50eae834ce57269eaaa215c
      Handler: br.com.trips.handler.CreateTrip::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        CreateTrip:
          Type: Api
          Properties:
            Path: /trips
            Method: post
  GetTripsByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://trips-bucket/cb9f89b3d50eae834ce57269eaaa215c
      Handler: br.com.trips.handler.GetTripsByCountry::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetTripsByCountry:
          Type: Api
          Properties:
            Path: /trips/{country}
            Method: get
          RequestParameters:
          - method.request.querystring.city
          - method.request.querystring.starts
          - method.request.querystring.ends
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
      - AttributeName: country
        AttributeType: S
      - AttributeName: travelDate
        AttributeType: S
      KeySchema:
      - AttributeName: country
        KeyType: HASH
      - AttributeName: travelDate
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateTripFunction:
    Description: CreateTrip Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripFunction
      - Arn
  GetTripsByCountryFunction:
    Description: GetTripsByCountry Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsByCountryFunction
      - Arn
